### ISSUE TITLE
Docker credentials leaked

### ISSUE THREAD

**Issue by andreaTP** [agavitalis/kaniko-kubernetes#1]
Hi @agavitalis ,

I'm going through your blog:
https://snyk.io/blog/building-docker-images-kubernetes/

and casually noticed this repo, unfortunately, seems like the `docker.io` credentials in the `Readme` are working:
![Screenshot 2022-09-16 at 15 33 55](https://user-images.githubusercontent.com/5792097/190664040-b8651f92-cd21-4fa1-bc20-c3b0cde9122a.png)

I encourage you to change the credentials and remove them from the repo.

And, thanks for the blog!

**Comment by agavitalis** [comment]
Thanks alot
